-- 1. What are the names of all the countries in the country table?

SELECT DISTINCT country_name AS Countires
FROM country;

-- 2. What is the total number of customers in the customers table?

SELECT COUNT(DISTINCT customer_id) AS 'Total Customers'
FROM customers;


-- 3. What is the average age of customers who can receive marketing emails (can_email is set to 'yes')?

SELECT AVG(age) AS 'Average Age'
FROM customers 
WHERE can_email = 'yes';


-- 4. How many orders were made by customers aged 30 or older?

SELECT COUNT(order_id) AS Orders
FROM customers c 
JOIN orders o ON c.customer_id = o.customer_id
WHERE age >=30;


-- 5. What is the total revenue generated by each product category?

SELECT p.category AS 'Product Category', SUM(p.price) AS 'Total Revenue'
FROM products p
JOIN baskets b ON p.product_id = b.product_id
GROUP BY p.category;


-- 6. What is the average price of products in the 'food' category?

SELECT AVG(price) AS 'Average Price'
FROM products
WHERE Category = 'food';


-- 7. How many orders were made in each sales channel (sales_channel column) in the orders table?

SELECT sales_channel AS 'Sales Channel', COUNT(order_id) AS 'Orders'
FROM orders
GROUP BY sales_channel
ORDER BY COUNT(order_id);


-- 8.What is the date of the latest order made by a customer who can receive marketing emails?

SELECT MAX(o.date_shop) AS 'Latest Order Date'
FROM orders o
JOIN customers c ON c.customer_id = o.customer_id
WHERE c.can_email = 'yes';


-- 9. What is the name of the country with the highest number of orders?

SELECT c.country_name AS 'Country', COUNT(order_id)
FROM country c
JOIN orders o ON c.country_id = o.country_id
GROUP BY c.country_name
ORDER BY COUNT(order_id) DESC
LIMIT 1;


-- 10. What is the average age of customers who made orders in the 'vitamins' product category?

SELECT ROUND(AVG(c.age), 0) AS 'Average Age'
FROM customers c
JOIN orders o ON c.customer_id = o.customer_id
JOIN baskets b ON b.order_id = o.order_id
JOIN products p ON p.product_id = b.product_id
WHERE p.category = 'vitamins';
